const projects={
 proteus:{kicker:'Honours project · Adaptive architecture',title:'Proteus™ Adaptive Wall System',description:'A modular aluminium wall system designed around change. Removable interior panels provide service access, while interchangeable exterior walls, windows and doors allow a home to adapt over its life. The project combines circular design principles, prototyping, technical development and real-world modular construction research.',image:'assets/proteus-wall-panels.png',links:[['Design exegesis','assets/proteus-exegesis.pdf'],['Drawing set','assets/proteus-drawing-set.pdf'],['Project proposal','assets/project-proposal.pdf']]},
 drill:{kicker:'Product development · CAD',title:'Cordless Drill',description:'A complete cordless drill concept developed through ergonomic form exploration, SolidWorks modelling and formal engineering documentation.',image:'assets/drill.jpg',links:[['Engineering drawings','assets/drill-engineering-drawings.pdf']]},
 stool:{kicker:'Furniture · Rendering',title:'Sculptural Bar Stool',description:'A furniture study using mirrored timber curves to create a lightweight visual rhythm while keeping the seat and structure grounded.',image:'assets/bar-stool.jpg',links:[]},
 desk:{kicker:'System design · SolidWorks',title:'Modular Desk System',description:'A flexible desk platform with adjustable legs and linkable corners, allowing individual units to form varied learning and working layouts.',image:'assets/modular-desk.jpg',links:[]},
 bag:{kicker:'Soft goods · Making',title:'Leather Shoulder Bag',description:'A functional shoulder bag made to explore leather pattern development, edge finishing, hardware integration and assembly by hand.',image:'assets/leather-bag.jpg',links:[]},
 mantis:{kicker:'Furniture · Fabrication',title:'Mantis Table',description:'A biomorphic side table developed through physical model-making. Its layered plywood structure turns natural movement into a functional furniture form.',image:'assets/mantis-table.jpg',links:[]},
 picnic:{kicker:'Manufacturing · Concept',title:'Rotational Moulded Picnic Table',description:'A public furniture concept designed around rotational moulding, using a continuous organic shell to create integrated seating and a central table.',image:'assets/picnic-table.jpg',links:[]},
 torch:{kicker:'Product design · Documentation',title:'Portable Torch',description:'A compact torch project focused on grip, carrying, assembly and the translation of three-dimensional form into technical views.',image:'assets/torch.jpg',links:[['Engineering drawing','assets/torch-engineering-drawing.pdf']]}
};
const menu=document.querySelector('.menu-button'),nav=document.querySelector('#site-nav');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const dialog=document.querySelector('.project-dialog'),media=dialog.querySelector('.dialog-media'),title=dialog.querySelector('#dialog-title'),kicker=dialog.querySelector('.dialog-kicker'),description=dialog.querySelector('.dialog-description'),links=dialog.querySelector('.dialog-links');
document.querySelectorAll('.project').forEach(card=>card.querySelector('button').addEventListener('click',()=>{const p=projects[card.dataset.project];title.textContent=p.title;kicker.textContent=p.kicker;description.textContent=p.description;media.className='dialog-media';media.innerHTML='';if(p.image){const img=new Image();img.src=p.image;img.alt=p.title;media.append(img)}else{media.classList.add('proteus-detail')}links.innerHTML=p.links.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener">${label} ↗</a>`).join('');dialog.showModal();document.body.style.overflow='hidden'}));
function closeDialog(){dialog.close();document.body.style.overflow=''}
dialog.querySelector('.dialog-close').addEventListener('click',closeDialog);dialog.addEventListener('click',e=>{if(e.target===dialog)closeDialog()});dialog.addEventListener('close',()=>document.body.style.overflow='');
